# Generated by Django 4.2.1 on 2023-06-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=15)),
                ('room_number', models.CharField(max_length=7)),
                ('capacity', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('building', models.CharField(blank=True, max_length=15, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('tot_cred', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('time_slot_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=1)),
                ('start_hr', models.DecimalField(decimal_places=0, max_digits=2)),
                ('start_min', models.DecimalField(decimal_places=0, max_digits=2)),
                ('end_hr', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('end_min', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'time_slot',
            },
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('s', models.OneToOneField(db_column='s_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.student')),
            ],
            options={
                'db_table': 'advisor',
            },
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.course')),
            ],
            options={
                'db_table': 'prereq',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.course')),
                ('sec_id', models.CharField(max_length=8, unique=True)),
                ('semester', models.CharField(max_length=6, unique=True)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('time_slot_id', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.student')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'takes',
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.instructor')),
            ],
            options={
                'db_table': 'teaches',
            },
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('time_slot_id', 'day', 'start_hr', 'start_min'), name='time_slot_id_day_start_hr_start_min'),
        ),
        migrations.AddField(
            model_name='student',
            name='dept_name',
            field=models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.department'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='dept_name',
            field=models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.department'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('building', 'room_number'), name='building_room_number'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.section'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='sec',
            field=models.ForeignKey(db_column='sec_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_sec_set', to='core.section', to_field='sec_id'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='semester',
            field=models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_semester_set', to='core.section', to_field='semester'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='year',
            field=models.ForeignKey(db_column='year', on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches_year_set', to='core.section', to_field='year'),
        ),
        migrations.AddField(
            model_name='takes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.section'),
        ),
        migrations.AddField(
            model_name='takes',
            name='sec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_sec_set', to='core.section', to_field='sec_id'),
        ),
        migrations.AddField(
            model_name='takes',
            name='semester',
            field=models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_semester_set', to='core.section', to_field='semester'),
        ),
        migrations.AddField(
            model_name='takes',
            name='year',
            field=models.ForeignKey(db_column='year', on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes_year_set', to='core.section', to_field='year'),
        ),
        migrations.AddField(
            model_name='section',
            name='room_id',
            field=models.ForeignKey(blank=True, db_column='ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_room_number_set', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='prereq',
            name='prereq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prereq_prereq_set', to='core.course'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='i',
            field=models.ForeignKey(blank=True, db_column='i_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.instructor'),
        ),
        migrations.AddConstraint(
            model_name='teaches',
            constraint=models.UniqueConstraint(fields=('id', 'course', 'sec', 'semester', 'year'), name='teaches_id_course_sec_semester_year'),
        ),
        migrations.AddConstraint(
            model_name='takes',
            constraint=models.UniqueConstraint(fields=('id', 'course', 'sec', 'semester', 'year'), name='takes_id_course_sec_semester_year'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'sec_id', 'semester', 'year'), name='course_sec_id_semester_year'),
        ),
        migrations.AddConstraint(
            model_name='prereq',
            constraint=models.UniqueConstraint(fields=('course', 'prereq'), name='course_prereq'),
        ),
    ]
