# Generated by Django 4.2.1 on 2023-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(blank=True, max_length=2, null=True),
        ),
    ]
