# Generated by Django 4.2.1 on 2023-06-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
