# Generated by Django 4.2.1 on 2023-06-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_takes_takes_id_course_sec_semester_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='s_id',
            field=models.OneToOneField(db_column='s_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaches',
            name='ins_id',
            field=models.OneToOneField(db_column='ins_ID', default=11, on_delete=django.db.models.deletion.DO_NOTHING, to='core.instructor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(db_column='ID', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='takes',
            name='id',
            field=models.CharField(db_column='ID', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='id',
            field=models.CharField(db_column='ID', max_length=4, primary_key=True, serialize=False),
        ),
    ]
