# Generated by Django 4.2.1 on 2023-06-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_takes_s_id_teaches_ins_id_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='s_id',
            field=models.ForeignKey(db_column='s_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='core.student'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='ins_id',
            field=models.ForeignKey(db_column='ins_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='core.instructor'),
        ),
    ]
