# Generated by Django 4.2.1 on 2023-06-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_takes_s_id_alter_teaches_ins_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(db_column='ID', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='takes',
            name='id',
            field=models.CharField(db_column='ID', max_length=4, primary_key=True, serialize=False),
        ),
    ]
