# Generated by Django 4.2 on 2023-06-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_student_id_alter_takes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.course'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.course'),
        ),
    ]
