# Generated by Django 4.2 on 2023-06-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_takes_course_alter_teaches_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='time_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.timeslot'),
        ),
    ]
